name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: mazidhossain/visitor-counter

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            ${{ env.DOCKER_IMAGE }}:latest

      - name: Set up kubeconfig (Minikube)
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Update Helm values with new image tag
        run: |
          sed -i "s|tag:.*|tag: ${{ github.sha }}|g" visitor-chart/values.yaml

      - name: Deploy with Helm
        run: |
          helm upgrade --install my-visitor ./visitor-chart