apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-visitor-service
spec:
  selector:
    app: visitor
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  type: {{ .Values.service.type }}